### ISSUE TITLE
plot a region of genbank file

### ISSUE THREAD

**Issue by webermarcolivier** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#12]
Is there a way to plot a region start..end of a Genbank file?

**Comment by Zulko** [comment]
Yes, with:

```python
cropped_record = record.crop((start, end))
cropped_record.plot()
```

**Comment by peterjc** [comment]
Beware that Biopython's ``SeqRecord`` cropping (which I assume is what the example shows) will only keep features fully within the crop region. Anything saddling the boundary is lost (trying to crop a feature and accurately describe it is filled with corner cases).

**Comment by Zulko** [comment]
Hello - this is taken into account, and the [``.crop()``](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/blob/67b469b0aa3f64f094a2b87c49018fca130a4f01/dna_features_viewer/GraphicRecord/GraphicRecord.py#L129) method implements its own cropping of the GraphicRecord (it doesn't crop the original SeqRecord). In the result, annotations saddling the boundaries are still there but marked as "open-ended" on the sides, as you would expect. See for instance example [``overview_and_detail.py``](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/blob/master/examples/overview_and_detail.py)

![](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/raw/master/examples/overview_and_detail.png)

**Comment by peterjc** [comment]
Excellent, I'd have to remind myself of the details but GenomeDiagram also had its own cropping (you give it a full record and tell it a start/stop), although I don't think we drew open ended edges like your example - that's a very nice visual cue.
