### ISSUE TITLE
Hard-coded font size in plot_sequence

### ISSUE THREAD

**Issue by webermarcolivier** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#13]
The `GraphicRecord:plot_sequence` function accepts a `fontdict` argument of which the `size` attribute is [hard-coded](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/blob/377c9e2b26ad9709c1afd7d01d1f8c1773c23e4a/dna_features_viewer/GraphicRecord.py#L280). Calling the function with `graphic_record.plot_sequence(ax=ax, fontdict={'size':6})` fails. Expected behavior would be to have a default font size that can be changed by `fontdict` argument.

**Comment by Zulko** [comment]
Thanks for catching that, I was using a complex syntax and it bit me. It should work now (fixed on Github and PyPI).
