### ISSUE TITLE
The "plot_with_bokeh" It doesn't work very well

### ISSUE THREAD

**Issue by EulleSA** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#17]
All the plots I've generated are getting like this. What can it be?
![Screenshot from 2019-10-08 17-51-32](https://user-images.githubusercontent.com/22760459/66427513-7d944980-e9ea-11e9-9680-59f8f0639594.png)

**Comment by Zulko** [comment]
Sorry for that, I made a lot of changes in the past few days without checking the compatibility with Bokeh (it's difficult to automatically test that bokeh is behaving correctly). I'll look into this tomorrow. Can you confirm that the same record is plotted fine on your machine, when you use the Matplotlib-based plot().

**Comment by EulleSA** [comment]
If it is the plot function that generates this type of image, yes it is working. The only problem I realized was with the chart shown earlier.
![Screenshot from 2019-10-08 21-37-58](https://user-images.githubusercontent.com/22760459/66443104-23a87980-ea14-11e9-871f-681548888888.png)
