### ISSUE TITLE
CroppingGraphicRecord.crop: ValueError at boundary condition

### ISSUE THREAD

**Issue by MrTomRod** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#20]
Hi!

I really enjoy your DnaFeaturesViewer!

I discovered a bug when cropping at the end of a graphic_record:

The graphic_record.span is `(0, 391390)`

I want to crop it as follows: `graphic_record.crop((388247, 391390))`

But this gets me a ValueError:

```
  File "project/gene_loci_comparison/gene_loci_comparison.py", line 71, in create_graphic_record
    graphic_record = graphic_record.crop(crop)
  File "venv/gene_loci_comparison/lib64/python3.7/site-packages/dna_features_viewer/GraphicRecord/GraphicRecord.py", line 116, in crop
    raise ValueError("out-of-bound cropping")
ValueError: out-of-bound cropping
```

If I crop `graphic_record.crop((388247, 391390 - 1))`, it works, but I loose a base at the end.

Thanks for this beautiful piece of software! :)

**Comment by Zulko** [comment]
Thanks for reporting this, this is now fixed. Please upgrade and let me know how it works (the last versions introduce many changes but hopefully nothing that will break your code, so let me know how it goes and what you think).

**Comment by MrTomRod** [comment]
Fix confirmed! For the record, this is version 2.2.0.

Nothing broke!

**Comment by MrTomRod** [comment]
Oh, the plots look different! I like it. :)

**Old:**
![image](https://user-images.githubusercontent.com/40867365/70310272-826d5200-180f-11ea-96bc-00d6615dae43.png)

**New:**
![image](https://user-images.githubusercontent.com/40867365/70310278-87320600-180f-11ea-8d25-856b6291108d.png)
