### ISSUE TITLE
Plotting a region reversed

### ISSUE THREAD

**Issue by MrTomRod** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#22]
It would be nice to be able to plot a genomic region in reverse.
I'm writing a script that allows me to compare the loci around the same genes in different species. Sometimes, the locus of interest is on the leading and sometimes on the lagging strand. I'd like to correct for this by discerning the orientation of the gene of interest and then to plot the region in reverse order if necessary.

**Example:**
Regular plot:
```python3
ax, _ = graphic_record.plot(figure_width=12)
```
![test_custom_colors](https://user-images.githubusercontent.com/40867365/71156881-3673d180-2241-11ea-8fd7-9819a53aa592.png)

Reversed plot:
```python3
graphic_record.reverse()  # new hypothetical function
ax, _ = graphic_record.plot(figure_width=12)
```
![test_custom_colors_reverse](https://user-images.githubusercontent.com/40867365/71156905-3ffd3980-2241-11ea-8453-89d274f05af6.png)

I'd be very happy if you could implement this.

**Comment by Zulko** [comment]
Got it. Not sure how easy it will be. A short term solution is to reverse your original Biopython record using ``record.reverse_complement()`` before you translate it to a graphic record. You would obtain the second figure, with the difference that the ruler's indices would be different, they would be relative to the (-) strand.

**Comment by Zulko** [comment]
Have you tried this? I haven't tried it but it could work:

```python
graphic_record.reverse()  # new hypothetical function
ax, _ = graphic_record.plot(figure_width=12)
x_start, x_end = ax.get_xlims()
ax.set_xlim(x_end, x_start)
```

**Comment by MrTomRod** [comment]
I tried it:
```
AttributeError: 'AxesSubplot' object has no attribute 'get_xlims'
```

I don't know what object to run this function on...

![Screenshot from 2019-12-19 10-45-41](https://user-images.githubusercontent.com/40867365/71163136-c5d2b200-224c-11ea-9398-acc862233342.png)

**Comment by Zulko** [comment]
Yay! Matplotlib saved the day. Thanks for the use case suggestion, I'll add this to the documentation.
