### ISSUE TITLE
Hidden bokeh tools

### ISSUE THREAD

**Issue by EulleSA** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#24]
The viewer tools are hidden or there has been some code change.

![Screenshot from 2020-01-10 14-44-04](https://user-images.githubusercontent.com/22760459/72174407-751c2800-33b8-11ea-80af-5263a1804467.png)

**Comment by Zulko** [comment]
Thanks for reporting this (I had indeed changed how the height is computed). I have now added a "minimal height" to bokeh plots to ensure that the icons can always be seen. Please upgrade and let me know if it works for you.

**Comment by EulleSA** [comment]
Thanks , man ! Its working perfectly !

**Comment by Zulko** [comment]
Awesome, closing the issue.
