### ISSUE TITLE
Current version '3.0.1' adds labels inside genome features

### ISSUE THREAD

**Issue by jolespin** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#33]
Current version: 
![image](https://user-images.githubusercontent.com/9061708/79264984-43e54500-7e4a-11ea-8b44-5ff479ee0a49.png)

Version from October 3, 2019:
![image](https://user-images.githubusercontent.com/9061708/79265072-637c6d80-7e4a-11ea-8224-f2bd366a0a8d.png)

Is there a way to control this behaviour? 

Also, why are there white lines for each xaxis tick?

**Comment by Zulko** [comment]
- Yes the new version has `record.plot(..., annotate_inline=True)` by default, use `annotate_inline=False` to have all labels floating above their features.
- Not sure at all why you have the white lines for each xaxis tick, looks like a bug but I dont see it on my machine. Could you share you OS, version of python and version of Matplotlib?

**Comment by jolespin** [comment]
OSX
![image](https://user-images.githubusercontent.com/9061708/79285775-5de74d80-7e73-11ea-9797-20a2c11b2096.png)

**Comment by Zulko** [comment]
Hmmm really not sure what is going on unfortunately. I have the same library version, same python version, and matplotlib  matplotlib 3.1.3. I can't see any problem.
