### ISSUE TITLE
Specify bokeh tools

### ISSUE THREAD

**Issue by MrTomRod** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#35]
I absolutely love this library, especially bokeh! I have a feature request, though:

It would be great if it were possible to specify the tools of the plot. Currently, I do it like this:

```python3
plot = graphic_record.plot_with_bokeh()

# remove hover tool
from bokeh.plotting._tools import process_tools_arg
tool_objs, tool_map = process_tools_arg(plot, "xpan,xwheel_zoom,reset,tap")
plot.tools = tool_objs
```
How I'd like it to work:
```python3
plot = graphic_record.plot_with_bokeh(tools=["xpan,xwheel_zoom,reset,tap"])
```

PS: In the function `plot_with_bokeh` of the class `BokehPlottableMixin` on [line 78](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/blob/master/dna_features_viewer/GraphicRecord/BokehPlottableMixin.py#L78), you have a silly print statement. :)

**Comment by veghp** [comment]
Thank you for the suggestion. Could you please perhaps make a pull request for this feature?

**Comment by veghp** [comment]
Thank you very much, I merged your PR
