### ISSUE TITLE
Zoom in the locally_highlighted_record result

### ISSUE THREAD

**Issue by J-I-P** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#39]
I upload the whole genome, and the result of the locally_highlighted_record is too small to recognize. Is any method can improve this problem?
I already set the parameter "figure_width=650".

**Comment by veghp** [comment]
Thank you for trying out DnaFeaturesViewer. Could you please post more information about what you tried and your intended outcome? Feel free to post the code -- or did you use the [CUBA app](https://cuba.genomefoundry.org/plot-sequence-features)?

DnaFeaturesViewer was designed with smaller sequences in mind (think plasmid), so your issue may be similar to https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/issues/34, where the solution was to make a small section of the genome and plot that instead.
