### ISSUE TITLE
Truncated labels

### ISSUE THREAD

**Issue by sejmodha** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#43]
Hi There,

I have recently come across this and must say that found this tool really useful! Thanks for developing it.
I have one small problem with feature display with long labels. Here is what I end up with, not sure what's causing it. 

<img width="211" alt="Screenshot 2020-09-25 at 16 06 38" src="https://user-images.githubusercontent.com/6159960/94284549-73948f00-ff4a-11ea-88d2-c7eda422bf32.png">

Can you please help to figure out how to fix it?

**Comment by Zulko** [comment]
Use `my_graphic_record.plot(... max_label_length=300)` to get longer labels (sorry just noticed that this parameter doesn't appear in the parameters description of `plot()`).

**Comment by sejmodha** [comment]
Perfect!
That resolved it, thanks for your help.

**Comment by veghp** [comment]
> this parameter doesn't appear in the parameters description of `plot()`).

I added this to the `dev` branch now.
