### ISSUE TITLE
no encoding declared in GraphicRecord.py

### ISSUE THREAD

**Issue by tniapp** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#49]
```
>>import dna_features_viewer

  File "~/libs/anaconda2/envs/py3/lib/python3.7/site-packages/dna_features_viewer/GraphicRecord/GraphicRecord.py", line 206
    label = label[: max_label_length - 1] + "…"
                                               ^
SyntaxError: Non-ASCII character '\xe2' in file ~libs/anaconda2/envs/py3/lib/python3.7/site-packages/dna_features_viewer/GraphicRecord/GraphicRecord.py on line 206, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by veghp** [comment]
Thanks for reporting this. What operating system are you using? The package was developed on Linux (Ubuntu) on Python 3.6.7, but should work on Mac as well. I tried in Python 3.7 too, but cannot reproduce the error. My suggested solution, following [this Q&A](https://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file): just open the file and add this to the top:

`# -*- coding: utf-8 -*-`

Alternatively, download the package with git and install in dev mode (`pip install -e .`).
