### ISSUE TITLE
Genebank to circular view

### ISSUE THREAD

**Issue by tobiv92** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#5]
I would like to plot a Genebank file not in the linear, but in the circular view.
Could you please provide code for that?
Thanks in advance.

**Comment by Zulko** [comment]
Use the following code:

```python
from dna_features_viewer import BiopythonTranslator, CircularGraphicRecord
translator = BiopythonTranslator()
circular_record = translator.translate_record(record_or_genbank_path,
                                              grecord_class=CircularGraphicRecord)
axes, infos = circular_record.plot(figure_width=12)
```

Note that the circular view does not get used often here. Hopefully everything will be alright for you.

**Comment by sarah872** [comment]
I am now getting the following error with the new release when trying the code from above:

     TypeError: translate_record() got an unexpected keyword argument 'grecord_class'

**Comment by Zulko** [comment]
I didn't like ``grecord`` so i changed the parameter to ``record_class`` (without the ``g``). Can you try this and tell me if it worked ?

**Comment by sarah872** [comment]
yep, thanks!
