### ISSUE TITLE
Change shape of feature arrows

### ISSUE THREAD

**Issue by Switham1** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#59]
Hello, thank you for making a great package.
Is there a way to change the shape of the feature arrows to a rectangle?
I tried pre-processing the records to change the sigil to BOX before passing to the translator but it doesn't seem to work.

e.g.:
```
for feature in seqrecord.features:
        #change sigil to box
        feature.qualifiers["sigil"] = 'BOX'
```
Many thanks,
Sam

**Comment by Zulko** [comment]
I believe that if the feature's strand is set to "0" you get a rectangle, would that work for you?

**Comment by Switham1** [comment]
Perfect thank you!
