### ISSUE TITLE
Error on BioPython v1.8.0

### ISSUE THREAD

**Issue by mbiokyle29** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#73]
We are getting the following error when using DnaFeaturesViewer with BioPython v1.8.0 ([tag](https://github.com/biopython/biopython/releases/tag/biopython-180)):
```python
In [5]: from dna_features_viewer import GraphicFeature
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 from dna_features_viewer import GraphicFeature

File .venv/lib/python3.8/site-packages/dna_features_viewer/__init__.py:3, in <module>
      1 """ dna_features_viewer/__init__.py """
----> 3 from .GraphicRecord import GraphicRecord
      4 from .CircularGraphicRecord import CircularGraphicRecord
      5 from .GraphicFeature import GraphicFeature

File .venv/lib/python3.8/site-packages/dna_features_viewer/GraphicRecord/__init__.py:1, in <module>
----> 1 from .GraphicRecord import GraphicRecord
      3 __all__ = ['GraphicRecord']

File .venv/lib/python3.8/site-packages/dna_features_viewer/GraphicRecord/GraphicRecord.py:1, in <module>
----> 1 from ..biotools import find_narrowest_text_wrap
      3 from Bio.Seq import Seq
      4 from Bio.SeqRecord import SeqRecord

File .venv/lib/python3.8/site-packages/dna_features_viewer/biotools.py:38, in <module>
     28     """Return the reverse-complement of the DNA sequence.
     29 
     30     For instance ``complement("ATGCCG")`` returns ``"GCCGTA"``.
     31 
     32     Uses BioPython for speed.
     33     """
     34     return complement(sequence)[::-1]
     37 aa_short_to_long_form_dict = {
---> 38     _aa1: _aa3[0] + _aa3[1:].lower() for (_aa1, _aa3) in zip(aa1 + "*", aa3 + ["*"])
     39 }
     42 def translate(dna_sequence, long_form=False):
     43     """Translate the DNA sequence into an amino-acids sequence MLKYQT...
     44 
     45     If long_form is true, a list of 3-letter amino acid representations
     46     is returned instead (['Ala', 'Ser', ...]).
     47     """

TypeError: can only concatenate tuple (not "str") to tuple
```

It appears the `aa1` and `aa3` objects were updated to a different structure.

**Comment by RealYHD** [comment]
Having this exact issue. I was worried I broke something in my Conda environment. I've confirmed this is also a problem with Biopython version 1.80 as well as 1.79. I didn't test older versions.

A cursory glance makes me think Biopython version 1.79 is the one with the breaking change as they mention changing how sequence objects store their data.

From their changelogs for 1.79,
> The Seq and MutableSeq classes in Bio.Seq now store their sequence contents as bytes and bytearray objects, respectively.
[- Biopython News](https://github.com/biopython/biopython/blob/dcf52bd4546410e1a60d39fbcd4c0041ec1e6fe6/NEWS.rst)

**Comment by mbiokyle29** [comment]
@RealYHD - interesting that you were experiencing the issue with `1.79`, we hard pinned `BioPython==1.79` in our requirements file and it resolved the issue for us.

**Comment by RealYHD** [comment]
@mbiokyle29 Ah my bad, I was using Jupyter Labs and it seems the kernel cached the 1.80 version of biopython. As you said, **1.79 works**, in that case, disregard what I said previously.

**Comment by veghp** [comment]
Thank you all for bringing attention to this, I'll work on it. We have tested the current release against 1.79, and that 1.80 was released on the same day this error surfaced suggests that the issue is with 1.80.

The [changelog](https://github.com/biopython/biopython/blob/master/NEWS.rst#18-november-2022-biopython-180) does not mention this although it may be related to the dict replacement.

In the meantime I agree pinning to 1.79 solves this, or using a separate [image](https://github.com/Edinburgh-Genome-Foundry/EGF_Docker_Jupyter) / environment. Thanks for understanding.

**Comment by mbiokyle29** [comment]
@veghp - thanks for the response and for all your work on this great package. It seems like quite a change for them to include in a minor release, so some fall out is to be expected.

**Comment by jbloom** [comment]
Just noting that I also have this issue with the new `biopython` 1.80.

**Comment by antonkulaga** [comment]
I have the same error, it broke all my code when biopython got updated :(
![Screenshot from 2022-12-02 01-59-46](https://user-images.githubusercontent.com/842436/205184419-bb661644-7f62-4f38-9821-e15c949717a5.png)

**Comment by antonkulaga** [comment]
Any updates on that? I have a pip package that depends on dna-features-viewer and it is currently broken (cannot have github dependencies in setup.py)

**Comment by Zulko** [comment]
@antonkulaga Have you tried pinning `biopython==1.79` in your dependencies? It's not ideal but should get you going until a fix is released.
