### ISSUE TITLE
Margin too small

### ISSUE THREAD

**Issue by sarah872** [Edinburgh-Genome-Foundry/DnaFeaturesViewer#9]
When visualising contigs with long feature names, the margin is too small so that the label gets cropped (see left of `0`). When outputting a svg I can modify that in Illustrator, but is tedious for many files. Can it be adjusted?
![10919c00007](https://user-images.githubusercontent.com/29072882/40083173-9f0fbdfe-5893-11e8-9826-14864d720a3c.png)

**Comment by Zulko** [comment]
Did you set ``bbox_inches="tight"`` in the ``savefig`` method ? If not, you should try.
